### ISSUE TITLE
sendKeys not working

### ISSUE THREAD

**Issue by sunilskd** [congsang/MobileGuru99Project#1]
Hi,

Thanks for sharing a wonderful mobile test project. I was able to run all the tests successfully.

Unfortunately I could not run sendKey related scenarios, when I have text boxes in my app.  Scripts are able to identify the elements, click, getText etc. But sendKeys alone is not working. Any clue?

**Comment by congsang** [comment]
Hi sunilskd,

**Comment by sangcnguyen** [comment]
Hi Sunilskd,

Can you share a snapshot of this?

**Comment by sunilskd** [comment]
here is the code I use for the specific step to enter user name to a text field.

 driver.findElement(By.xpath("//android.view.View/android.widget.EditText[@text='Email or User Name']")).click();
 driver.findElement(By.xpath("//android.view.View/android.widget.EditText[@text='Email or User Name']")).sendKeys("userName@abc.com");

This text field has helper text " Email or User Name". So i tried different combinations of clearing the text first and then send keys, no luck.
I tried other combination of xpath with index, without text etc  and no luck.

As I mentioned earlier , Appium able to find the text box field, getText() works but not sendKeys.

Here is Appium log


[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["userName@abc.com"],"3","7ffef654-645d-4af0-affb-066c28853552"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"3","text":"userName@abc.com","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"3","text":"userName@abc.com","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 3
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Text remains after clearing, but it appears to be hint text.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Text not cleared. Assuming remainder is hint text.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending plain text to element: userName@abc.com
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.setValue() result: true

**Comment by sangcnguyen** [comment]
Hi Sunilskd,

I think you got the xpath wrong here, you just need to combine the class and the text, it will run.
For example: driver.findElement(By.xpath("//android.widget.EditText[@text='Email or User Name']"));

**Comment by sunilskd** [comment]
Thanks for the reply.

I tried with all the combinations of xpaths and none worked. I tried the xpath you mentioned too, still no luck. Can you try a test case with entering text to text box in your app or any open source app? Unfortunately I cannot share my app.

**Comment by sangcnguyen** [comment]
Sure, I can pass the test case with that combination.
Can you show me the text box structure by screen capture on the uiautomatorviewer tool? 
Like this
 

![capture](https://user-images.githubusercontent.com/14201772/34571703-c532ada6-f1a1-11e7-87ab-b18be2058c8a.PNG)

**Comment by sunilskd** [comment]
Attached the uiautomatorviewer. 

Here is the latest Appium logs too-

[BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.EditText[@text='Driver Email or User Name']","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.EditText[@text='Driver Email or User Name']' using 'XPATH' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.EditText, INSTANCE=0]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"1"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"1"}
[HTTP] <-- POST /wd/hub/session/168d2c58-bf8a-4115-a186-76f7716fb3a5/element 200 344 ms - 87
[HTTP] --> POST /wd/hub/session/168d2c58-bf8a-4115-a186-76f7716fb3a5/element/1/value {"id":"1","value":["test"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["test"],"1","168d2c58-bf8a-4115-a186-76f7716fb3a5"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"test","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"test","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 1
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Could not check for hint text because the element is not focused!
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Clearing text not successful. Attempting to clear by selecting all and deleting.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Could not check for hint text because the element is not focused!
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Clearing text not successful. Attempting to clear by sending delete keys.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Could not check for hint text because the element is not focused!
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Exhausted all means to clear text but 'Driver Email or User Name' remains.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Text not cleared. Assuming remainder is hint text.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending plain text to element: test
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.setValue() result: true

![login](https://user-images.githubusercontent.com/17894374/34575162-5780702a-f13f-11e7-9308-a7f3a58e8bf2.png)

**Comment by sangcnguyen** [comment]
I see you find the element on Android hybrid app.
For the hybrid app, you must change the view to webview. then only you can process the elements

Set contextNames = driver.getContextHandles();
for (String contextName : contextNames) {
System.out.println(contextNames);
}
it will print the context as Native,"WEBVIEW_com.xxx.yyy.zzzz", then you have to change the context to WEBVIEW in order to automate the hybrid app.

eg: driver.context("WEBVIEW_com.xxx.yyy.zzzz");
driver.context -->it will switch the context .

**Comment by sunilskd** [comment]
I tried with driver.context("WEBVIEW_io.ionic.starter"); for my app.

This time I cant identify any element , I mean driver.findElement(By.xpath("//android.widget.EditText[@text='Driver Email or User Name']"))    doesnt find any element :(.   

Earlier in Native app context, I was able to find , click etc. Only issue was sendKeys. When I set to webview context I cant find elements it self. I tried with multiple xpaths combination and no luck.

I know this is not your issue, but it would be great if you have a solution for this issue.

**Comment by sangcnguyen** [comment]
I've never encountered this situation before, but I have a solution for you. You need to follow the instructions in [this article](https://huddle.eurostarsoftwaretesting.com/appium-testing-web-views-appium/) and then redefine the xpath location in the webview element.

**Comment by sunilskd** [comment]
Thanks. the default context works fine on my Samsung s4 device , but not on my s8 device. I will further investigate into this. Thanks for your inputs.
